name: frontend_mistiwasi
description: "Sistema de gestión para AirBNB MistiWasi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase
  supabase_flutter: ^2.5.6
  
  # State Management
  provider: ^6.1.2
  
  # HTTP & Network
  http: ^1.2.1
  
  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  
  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.5
  uuid: ^4.3.3
  
  # Windows Desktop
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/